In [50]:
import pandas as pd
import numpy as np

In [51]:
df = pd.DataFrame([[8, 8, 4], [7, 9, 5], [6, 10, 6], [5, 12, 7]], columns=['cgpa', 'profile_score', 'lpa'])

In [52]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [62]:
import tensorflow
from tensorflow import keras
from keras import layers
from tensorflow.keras.layers import Dense

In [63]:
model = Sequential()
model.add(Dense(2,activation = 'linear', input_dim=2))
model.add(Dense(1,activation = 'linear'))

In [64]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (None, 2)                 6         
                                                                 
 dense_5 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9 (36.00 Byte)
Trainable params: 9 (36.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [65]:
model.get_weights()

[array([[ 1.1768817 ,  0.8384489 ],
        [-0.10282123, -0.712624  ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.05685639],
        [-0.9489359 ]], dtype=float32),
 array([0.], dtype=float32)]

In [66]:
new_weights = [
    np.array([[0.1, 0.1],[0.1,0.1]],dtype=np.float32), # Weight array for first dense layer
    np.array([0.,0.],dtype = np.float32), # Bias array for first dense layer
    np.array([[0.1],[0.1]],dtype = np.float32), # Weight array for second dense layer
    np.array([0.1],dtype = np.float32) # Bias array for second dense layer
]

model.set_weights(new_weights)

In [67]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.1], dtype=float32)]

In [69]:
optimizer = keras.optimizers.Adam(learning_rate=0.01)
model.compile(optimizer=optimizer, loss='mse')

In [73]:
model.fit(df[['cgpa','profile_score']],df.lpa,epochs=10)

Epoch 1/10
1/1 [==============================] - 0s 23ms/step - loss: 0.0297
Epoch 2/10
1/1 [==============================] - 0s 10ms/step - loss: 0.0296
Epoch 3/10
1/1 [==============================] - 0s 14ms/step - loss: 0.0296
Epoch 4/10
1/1 [==============================] - 0s 15ms/step - loss: 0.0296
Epoch 5/10
1/1 [==============================] - 0s 18ms/step - loss: 0.0296
Epoch 6/10
1/1 [==============================] - 0s 12ms/step - loss: 0.0296
Epoch 7/10
1/1 [==============================] - 0s 8ms/step - loss: 0.0296
Epoch 8/10
1/1 [==============================] - 0s 8ms/step - loss: 0.0296
Epoch 9/10
1/1 [==============================] - 0s 8ms/step - loss: 0.0296
Epoch 10/10
1/1 [==============================] - 0s 8ms/step - loss: 0.0296


In [74]:
model.get_weights()

[array([[-0.17332841, -0.17332841],
        [ 0.6329035 ,  0.6329035 ]], dtype=float32),
 array([0.1882223, 0.1882223], dtype=float32),
 array([[0.49388522],
        [0.49388522]], dtype=float32),
 array([0.32941306], dtype=float32)]