In [5]:
import numpy as np
import pandas as pd


In [9]:
df = pd.DataFrame([[8,8,1],[7,9,1],[6,10,0],[5,5,0]],columns=['cgpa','profile_score','placement'])
df

cgpa  profile_score  placement
0     8              8          1
1     7              9          1
2     6             10          0
3     5              5          0

In [12]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [13]:
model = Sequential()
model.add(Dense(2,activation = 'sigmoid', input_dim=2))
model.add(Dense(1,activation = 'sigmoid'))

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 6         
                                                                 
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9 (36.00 Byte)
Trainable params: 9 (36.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [15]:
model.get_weights()

[array([[-0.21073055, -0.13218284],
        [-0.42467213,  0.06676102]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.24449289],
        [-0.7624958 ]], dtype=float32),
 array([0.], dtype=float32)]

In [16]:
new_weights = [
    np.array([[0.1, 0.1],[0.1,0.1]],dtype=np.float32), # Weight array for first dense layer
    np.array([0.,0.],dtype = np.float32), # Bias array for first dense layer
    np.array([[0.1],[0.1]],dtype = np.float32), # Weight array for second dense layer
    np.array([0.1],dtype = np.float32) # Bias array for second dense layer
]

model.set_weights(new_weights)

In [17]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.1], dtype=float32)]

In [18]:
optimizer = keras.optimizers.Adam(learning_rate=0.01)
model.compile(optimizer=optimizer, loss='mse')

In [21]:
model.fit(df[['cgpa','profile_score']],df.placement,epochs=20)

Epoch 1/20
1/1 [==============================] - 0s 10ms/step - loss: 0.2499
Epoch 2/20
1/1 [==============================] - 0s 9ms/step - loss: 0.2499
Epoch 3/20
1/1 [==============================] - 0s 9ms/step - loss: 0.2499
Epoch 4/20
1/1 [==============================] - 0s 7ms/step - loss: 0.2499
Epoch 5/20
1/1 [==============================] - 0s 7ms/step - loss: 0.2499
Epoch 6/20
1/1 [==============================] - 0s 9ms/step - loss: 0.2499
Epoch 7/20
1/1 [==============================] - 0s 7ms/step - loss: 0.2499
Epoch 8/20
1/1 [==============================] - 0s 8ms/step - loss: 0.2499
Epoch 9/20
1/1 [==============================] - 0s 9ms/step - loss: 0.2498
Epoch 10/20
1/1 [==============================] - 0s 9ms/step - loss: 0.2497
Epoch 11/20
1/1 [==============================] - 0s 9ms/step - loss: 0.2496
Epoch 12/20
1/1 [==============================] - 0s 9ms/step - loss: 0.2495
Epoch 13/20
1/1 [==============================] - 0s 9ms/step - loss: 0

In [22]:
model.get_weights()

[array([[ 0.23510756,  0.23510756],
        [-0.02663687, -0.02663687]], dtype=float32),
 array([-0.17586151, -0.17586151], dtype=float32),
 array([[0.08620352],
        [0.08620352]], dtype=float32),
 array([-0.06053696], dtype=float32)]